### ISSUE TITLE
Unexpected token error when using call and receive

### ISSUE THREAD

**Issue by nvenk** [fwextensions/figma-await-call#1]
Fairly new to development, so this could be my own error, but I get this error when using `receive`. Everything works fine when using the regular `onmessage` syntax.

![CleanShot 2023-12-05 at 17 50 21@2x](https://github.com/fwextensions/figma-await-ipc/assets/10296649/d73ef51c-391a-4f43-bef0-1fb8d6b31261)

Thanks for your work on this! It's exactly what I was looking for, and improves code readability by so much! I don't really need async features, but found this when just looking for a cleaner, easier way to send messages between the UI and main contexts.

**Comment by fwextensions** [comment]
Sorry for the slow response!  Missed this during the holidays.

Hopefully you've gotten this sorted, but it looks like whatever you're using to run this code, or maybe to package it, doesn't support the optional chaining operator, which is has been around for about 4 years.  I *think* that operator is supported in the Figma plugin environment.  I usually use `create-figma-plugin` to build and package plugins, and that seems to convert all the code to an older target when it's built, which replaces the optional chaining operator.  But I don't think it does when you're running the dev server, so this line in the screenshot shouldn't be an issue.

Anyway, let me know if you're still seeing this.
